### PR TITLE
Update Alpine to 3.10.3 + improvements

### PR DESCRIPTION
**Pull request by xZero707**
Alpine 3.10.3
Improvements over download and installation process.

### CODE REVIEW

**Comment by xZero707** [comment]
Unfortunately this project seems to be abandoned, so I'll be closing this pull request, and continue to maintain independent fork.

**Comment by skarnet** [comment]
Abandoned? That would be a shame. Checking with @glerchundi.

**Comment by xZero707** [comment]
@skarnet Let me know. 
Looks abandoned at least. No commits for over 3 years. Pull requests ignored. The base image is outdated as well.  
Shall this project live, I'll reopen pull request, and delete my fork afterward.

**Comment by skarnet** [comment]
If @glerchundi hasn't answered by next week-end, please ping me. I should be able to merge PRs. I'm not saying I'll maintain the project, but a simple update to the latest Alpine version shouldn't be too hard to review and merge.

**Comment by xZero707** [comment]
Sure. :+1: 

There are projects pout there that got abandoned, whilst there is a bunch of contributors willing to contribute, but nobody to accept contributions. As long as there is someone to merge PR-s, project will live.

**Comment by skarnet** [comment]
Also putting @jprjr in the loop because all of this is his fault after all ;-)

**Comment by glerchundi** [comment]
Thanks for the contribution & sorry for not answering before. Last two years were really tough. 

Perhaps it's time to call for maintainers as I don't expect to be available in the near future.

**Comment by xZero707** [comment]
Since I have started maintaining my own fork, I've changed maintainer to myself. Merging my pull request included all changes on my fork. Perhaps you want to re-include yourself. Since this project lives,  I am dismantling my fork and docker hub repo.

I've noticed that build on Quay is failing, but I can't see why. Can you forward me the error details, please? 
Build on Docker hub as well as my local machine(s) works well. 
Opera Snapshot_2019-11-08_095716_hub docker com

**Pull request merged**
